version: "2"
services:
  node:
    container_name: cos426-game-server
    build: ./docker/server.Dockerfile
    user: "node"
    working_dir: /home/node/server
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./dist
        target: /home/node/server
        read_only: true
    command: "node index.bundle.js"
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:alpine
    environment:
      - NGROK_AUTHTOKEN=2HaQ4BuVSOIFRo57Epo4Dfkb9FS_5Gu8x8ubgzzHegMWKHN5V
    ports:
      - 4040:4040
    command: "http https://final:8080/" 
